#!/usr/bin/env bash
# Builds supabase/production/setup.sql: every migration, in order, as one file
# to paste into the Supabase SQL editor on a new project. No demo data.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/supabase/production/setup.sql"
{
  echo "-- Stockline database setup for a NEW Supabase project."
  echo "-- Paste this whole file into Supabase → SQL Editor → New query, then Run."
  echo "-- Generated by scripts/build-production-sql.sh from supabase/migrations. Do not edit by hand."
  echo "-- Contains the schema, security rules and business logic only: no demo data."
  echo
  for f in "$ROOT"/supabase/migrations/*.sql; do
    echo "-- ============================================================================"
    echo "-- $(basename "$f")"
    echo "-- ============================================================================"
    cat "$f"
    echo
  done
  echo "notify pgrst, 'reload schema';"
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines, $(du -h "$OUT" | cut -f1))"
